spring:
  application:
    name: tanhua-dubbo-db
  datasource:
    url: jdbc:mysql://localhost:3306/tanhua?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.129:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 20881 # 让系统自动选择
  scan:
    base-packages: com.tanhua.dubbo.api
  cloud:
    # /代表 不订阅服务
    subscribed-services: /
mybatis-plus:
  global-config:
    db-config:
      #表名前缀 全局配置
      table-prefix: tb_
      #id自增 全局配置
      id-type: auto

logging:
  pattern:
    # 输出到控制台
    console: '%d{HH:mm:ss.SSS} %-5level %msg [%thread] - %logger{15}%n\'
  level:
    root: info # 全局用info
    # 只有在com.itheima包下才输出debug信息
    com:
      tanhua: debug